sudo: false

language: python

python:
  - "3.4"

env:
  - TOXENV=py34-django18,py35-django18
  - TOXENV=py34-django19,py35-django19

install:
    - pip install tox pip wheel -U

script:
    - tox

branches:
  only:
    - master
