sudo: false

language: python

python:
  - "3.4"

env:
  - TOXENV=py34-django18,py35-django18
  - TOXENV=py34-django19,py35-django19

install:
  - pip install tox pip wheel codecov -U

script:
  - tox

after_success:
  - codecov -e TOX_ENV

branches:
  only:
    - master
